import type { Post } from "../posts";
export const postOrder = 5;

export const post: Post = {
    slug: "anant-chaturdashi-2026-date-puja-anant-sutra",
    title: "Anant Chaturdashi 2026: date, Vishnu puja, Anant Sutra and Ganesh Visarjan",
    date: "2026-09-20",
    updated: "20 September 2026",
    tag: "Festivals",
    excerpt: "Anant Chaturdashi 2026 is on 25 September. Understand the Vishnu vrat, 14-knot Anant Sutra, Kaundinya-Sushila katha and the final Ganesh Visarjan day.",
    body: [
      { p: "Anant Chaturdashi in 2026 is on Friday, 25 September. In Mumbai and New Delhi, Drik Panchang places Shukla Chaturdashi from 11:18 pm on 24 September to 11:06 pm on 25 September. The day carries two observances that are often folded into one headline but should be understood separately: the Ananta vrat dedicated to Vishnu, and the final day of Ganeshotsav, when many public and household Ganpatis are immersed." },
      { p: "If your search is only about the Ganesh Visarjan procession, the answer is still 25 September. But Anant Chaturdashi did not begin as another name for Ganesh Visarjan. The older vrata tradition centres Ananta, the infinite form of Vishnu; Yamuna; Shesha; a fourteen-knotted sacred thread; fasting; and the story of Sushila and Kaundinya. In Maharashtra, the festival calendar brings that Vishnu vrat and Bappa's farewell onto the same day." },
      { note: "The short answer: Anant Chaturdashi 2026 is Friday, 25 September. For Mumbai, the puja period shown by Drik Panchang runs from 6:28 am until the tithi ends at 11:06 pm. Exact clock times are location-specific." },
      { photo: "anantaPadmanabhaKarkala", caption: "Ananta Padmanabha, Vishnu reclining on Ananta, at the protected temple monument in Karkala." },

      { h: "Anant Chaturdashi 2026 date and puja time" },
      { table: { head: ["What", "2026 timing"], rows: [
        ["Anant Chaturdashi", "Friday, 25 September 2026"],
        ["Chaturdashi tithi begins", "11:18 pm on Thursday, 24 September"],
        ["Chaturdashi tithi ends", "11:06 pm on Friday, 25 September"],
        ["Mumbai puja period", "6:28 am to 11:06 pm on 25 September"],
        ["New Delhi puja period", "6:11 am to 11:06 pm on 25 September"],
      ] } },
      { p: "The Mumbai and Delhi calculations agree on the tithi boundary but give different morning openings because sunrise and the local day division vary by city. This is why a puja time copied from a generic search result should never be labelled 'for all India'. Enter your location in the panchang your household uses." },
      { p: "The late start on 24 September is not a reason to keep the vrat on Thursday night. The observance is on Friday, when Chaturdashi is present through the day. For a public immersion, panchang time is only one layer. Municipal immersion-site hours, traffic closures, procession routes, tide and weather warnings are live facts that must be checked on the day." },

      { h: "What Anant Chaturdashi means" },
      { p: "Ananta means endless or infinite. In this vrata, Ananta is Vishnu, often visualised as Padmanabha reclining on the serpent Ananta-Shesha. The image is not decorative background: Vishnu rests on the coils of the endless serpent, while the lotus associated with creation rises from his navel. The festival asks the worshipper to think beyond one difficult season or one prosperous season toward what sustains life through change." },
      { p: "Drik Panchang describes worship of Vishnu, Yamuna and Sheshnag, followed by tying the Anant Sutra. A detailed ritual account from Sanatan Sanstha likewise gives Yamuna puja, Shesha worship and worship of the thread as distinct parts. ISKCON Dwarka presents the date as the appearance day of Padmanabha and emphasises the same central elements: an image or symbol of Padmanabha, flowers, fruit, sweets, fasting, the thread and the vrata-katha." },
      { p: "That is already enough to show why Anant Chaturdashi is not simply 'the last Ganpati day'. The two observances coexist. A Maharashtrian household may perform Ganpati's Uttar Puja and farewell without keeping the Ananta vrata. Another family may keep the Vishnu vrata without having installed Ganpati. A third may do both, but as two recognisable sequences rather than one invented hybrid ritual." },

      { h: "The Anant Sutra and its fourteen knots" },
      { p: "The most visible object in the vrata is the Anant Sutra, also called Ananta dhaga: a sacred thread with fourteen knots. Drik Panchang explains the knots as representing the fourteen worlds. Temple and vrata guides describe worshipping the thread before it is tied, so it is not meant to be worn as a festival-coloured accessory bought on the way to work." },
      { p: "Many current guides state that men tie it on the right arm and women on the left. ISKCON Dwarka gives that convention. Regional and family practices can still differ, and the thread may be prepared, coloured and tied differently. If this is a formal vrata in your family, ask the person who taught it how the thread is prepared, who ties it, and when an older thread is removed." },
      { h3: "Do not invent the fourteen knots at the last minute" },
      { p: "Buy or prepare the thread before the puja, and count the knots while there is time to correct them. Keep it with the puja items rather than treating it as ordinary craft string. During the worship, offer gandha, akshat and flowers according to the sequence you follow. Tie it only after the worship is complete." },
      { p: "The internet gives conflicting rules for how long the thread stays on. Sanatan Sanstha's published replies acknowledge more than one tradition: some remove it after fourteen days and keep it in the home shrine until the next year's donation; some retain it longer and replace it at the next vrata. That disagreement is a reason to follow your local purohit or inherited custom, not a reason to declare one family's practice wrong." },
      { note: "The Anant Sutra has a specific place in a vrata. If you are not undertaking that vrata, do not tie a random fourteen-knot thread because a reel promised protection. Learn the sankalp and conclusion from your family priest or tradition first." },

      { h: "A practical home puja outline" },
      { p: "A full Ananta vrata can be detailed. Sanatan Sanstha's account includes separate worship of Yamuna, a darbha representation of Shesha, the consecrated threads and multiple offerings. A household already initiated into that sequence should use its book and priest. A first-time worshipper should not compress a long formal rite into a list assembled from snippets." },
      { p: "For a simple Vishnu puja marking the day, without claiming to undertake every obligation of the formal vrata, arrange a clean altar with an image of Vishnu or Ananta Padmanabha, a diya, water, flowers, tulsi, fruit and a sattvic sweet. If you are formally keeping the vrata, add the prescribed kalasha, Yamuna and Shesha representations, and properly prepared Anant Sutra according to your family's method." },
      { h3: "Before beginning" },
      { ul: [
        "Check the local tithi and choose a calm puja time within it.",
        "Decide whether you are doing simple Vishnu worship or formally taking the Ananta vrata. Do not blur the two after beginning.",
        "Bathe, clean the puja place and set out every item before lighting the lamp.",
        "Prepare the naivedya without onion, garlic, egg or meat if that is the standard of your Vishnu worship.",
        "Keep the katha text or recording ready from a source you trust.",
      ] },
      { h3: "A simple sequence" },
      { p: "1. Light the diya and make your sankalp. Name the date and say whether you are offering a simple puja or observing the vrata received in your family. Ask for steadiness, not a guaranteed transaction in which one day's ritual must produce wealth." },
      { p: "2. Invoke Vishnu and offer water, sandalwood, akshat, flowers and tulsi according to your practice. If Yamuna and Shesha are part of your vrata sequence, worship them in the prescribed order rather than mentioning them only in a concluding prayer." },
      { p: "3. Worship the fourteen-knotted Anant Sutra. Offer the materials taught in your method, recite the mantra from your vrata text, and tie the thread on the correct arm after worship. Do not tie it so tightly that it restricts circulation." },
      { p: "4. Offer fruit and naivedya. Read or hear the Ananta vrata-katha. Perform aarti, offer pranam and distribute prasad. If a priest is guiding the vrata, follow the conclusion and donation instructions they give." },
      { p: "5. Keep the rest of the day consistent with the vrata you chose. A strict fast, fruit fast, one meal or simple sattvic discipline should be decided with health and medication in mind. There is no devotional gain in hiding a medical need." },

      { h: "The story of Sushila and Kaundinya" },
      { p: "The Anant Chaturdashi katha is commonly identified as the story of Sushila and the sage Kaundinya, also written Kaundilya. The outline matters because it explains the thread as a vow rather than a charm." },
      { p: "Sushila learns the Ananta vrata, performs the worship and ties the sacred thread. Her household prospers. Kaundinya later sees the thread, misunderstands or rejects it, and destroys it. Their prosperity collapses. He then wanders in search of Ananta, meeting strange and suffering figures on the way. After repentance and instruction, he undertakes the vrata and their life is restored." },
      { p: "Tellings vary in the exact meetings, dialogue, duration and moral emphasis. Some narrators turn the story into a blunt formula: wear a thread and receive money. The more careful reading is about arrogance, a vow broken in contempt, recognition of dependence, and disciplined return. Prosperity in the story is not permission for a seller to guarantee a financial result from a packet of thread." },
      { p: "If reading aloud with children, pause at Kaundinya's reaction. Ask why he dismisses something Sushila undertook with care, and what it means to apologise through changed conduct rather than words alone. That makes the katha a family conversation, not background audio playing while everyone checks messages." },

      { h: "Fasting and food on Anant Chaturdashi" },
      { p: "Fasting is common in the Ananta vrata. The strictness varies by lineage and health. ISKCON Dwarka describes a day-long fast, while everyday household observance may use fruit, milk or one sattvic meal. Decide with the tradition you follow and the needs of your body." },
      { p: "Sanatan Sanstha records sweet puris made with pumpkin as a special naivedya in its ritual tradition. Other households offer kheer, fruit, puri, halwa or the foods prescribed in their regional vrata book. The existence of one detailed menu does not make every other home incomplete. It does mean a writer should not silently replace the vrata's own offering with whatever recipe happens to rank that week." },
      { ul: [
        "Prepare the offering before the main puja so the thread worship and katha are not interrupted by cooking.",
        "Reserve the offering portion in a clean vessel before tasting, if that is your family rule.",
        "If fasting with medication, take the food your doctor or medicine requires.",
        "Share prasad while it is safe. Food is not meant to be added to immersion water.",
      ] },

      { h: "How Ganesh Visarjan fits into the day" },
      { p: "Ganeshotsav begins on Shukla Chaturthi and reaches its final public immersion day on Shukla Chaturdashi. In 2026, Ganesh Chaturthi was 14 September and Anant Chaturdashi is 25 September. Large mandals and households keeping Bappa for the full festival perform the concluding worship and join authorised immersion arrangements." },
      { p: "Ganpati's Uttar Puja is a farewell sequence. The Ananta vrata is Vishnu worship. If your home does both, finish each according to its own order. Do not tie the Anant Sutra to the Ganesh idol, put it into immersion water, or treat it as part of the idol's decoration unless your received tradition explicitly says so." },
      { p: "Before Ganesh Visarjan, remove plastic, electrical lights, synthetic cloth, batteries and other non-immersible decoration. Separate flowers and nirmalya according to the civic collection system. Share edible naivedya as prasad. A small natural-clay idol may be suitable for a controlled home immersion when local rules and family practice allow it; a large, painted, supported or plaster idol belongs in the authorised system." },
      { p: "On 25 September, check the current municipal list of immersion points, police diversions, site hours, weather and tide warnings. Do not rely on a last year's route map. The spiritually correct date does not cancel practical safety." },
      { photo: "anantChaturdashiVisarjan", caption: "A Ganesh idol immersion photographed on Anant Chaturdashi in Nashik." },

      { h: "If your family does both observances" },
      { table: { head: ["Ananta vrata", "Ganesh Visarjan"], rows: [
        ["Dedicated to Vishnu as Ananta or Padmanabha", "The concluding farewell to the installed festival form of Ganpati"],
        ["Centres Yamuna, Shesha and the fourteen-knot Anant Sutra in the formal sequence", "Centres Uttar Puja, final naivedya, aarti and safe immersion"],
        ["Includes the Sushila-Kaundinya katha", "Includes the household's farewell prayer and chants"],
        ["Thread is worshipped and tied on the arm", "Idol and immersion materials are prepared for the authorised site"],
      ] } },
      { p: "Make two trays if that prevents confusion. Keep the Anant Sutra and Vishnu-puja materials together. Keep Ganpati's final flowers, durva, naivedya and carrying arrangements together. One person can lead the thread puja while another checks the immersion route, but do not let logistics erase the katha or rush the Uttar Puja." },
      { p: "If the procession leaves early, ask your priest how to order the observances within the valid tithi. If it leaves late, protect enough time for rest and food, particularly for elders, children and anyone who fasted. The day can run for many hours in a large city." },

      { h: "What the YouTube search tells us, and what it cannot" },
      { p: "Current YouTube results for Anant Chaturdashi 2026 cluster around four phrases: kab hai, puja vidhi, vrat katha and chaudah gaanth wala Anant Sutra. The strongest established 2026 result in a search checked on 20 September had about 29,000 views, while many hastily published date videos had only dozens or hundreds. The useful signal is the question people need answered, not the confidence of the thumbnail." },
      { p: "Video is good for seeing how a thread is knotted, how a puja space is arranged and how a family stages the two observances. It is weak evidence for universal rules. One household's demonstration proves that household does it that way. It does not prove a mandate across Maharashtra, north India and south Indian Padmanabha traditions." },
      { p: "Use video to understand the physical sequence, then verify date and tithi with a local panchang and verify formal vrata rules with the temple, priest or book your family trusts. Be cautious with titles promising that one mistake causes disaster or one action guarantees lost wealth will return." },

      { h: "What to ask before joining someone else's puja" },
      { p: "Anant Chaturdashi practice differs enough that a guest should ask rather than arrive with a fixed internet sequence. Find out whether the household is keeping the Vishnu vrata, taking Ganpati for immersion, or doing both. Ask when the katha begins, whether the fast is still running, and whether they want food brought before or after puja. A box of ordinary sweets may contain ingredients their fast excludes." },
      { p: "If you are bringing an Anant Sutra, do so only after asking. The host may prepare threads at home, receive them from a priest, or use a colour and knotting method specific to the family. An unrequested thread creates pressure to use an object that may not fit their vrata. Flowers, fruit or help with post-puja food are safer unless you know the custom." },
      { p: "For a Ganesh Visarjan household, useful help is concrete: stay with an elder who cannot walk the procession, carry drinking water, manage the dry-waste bag, or arrange the ride home. Do not volunteer to carry the idol without knowing its weight and route. Do not livestream the puja or katha unless the host has agreed; a family vow is not automatically public content." },
      { lifafaCta: { text: "If you cannot be there for the vrat or visarjan, your own words can still arrive with the family.", label: "Send your shagun" } },

      { h3: "If you are away from family" },
      { p: "Join the reading or aarti by call if the family welcomes it, but ask for the actual time rather than relying on a forwarded muhurat card. If you want to send money, say what you hope it helps with: puja flowers, prasad, transport after visarjan or a meal for the people who did the carrying. Specific care feels warmer than a copied greeting." },

      { h: "A checklist for 25 September" },
      { h3: "For Ananta puja" },
      { ul: [
        "Local panchang time checked.",
        "Vishnu or Ananta Padmanabha image and clean altar.",
        "Formal vrata materials, including Yamuna and Shesha representations, if your tradition requires them.",
        "Fourteen-knot Anant Sutra prepared and counted.",
        "Flowers, tulsi, diya, water, akshat and naivedya.",
        "Katha text from a source you trust.",
      ] },
      { h3: "For Ganesh Visarjan" },
      { ul: [
        "Final naivedya and Uttar Puja sequence ready.",
        "Non-immersible decorations removed.",
        "Enough adults for the idol's actual weight.",
        "Authorised immersion site, route and hours rechecked.",
        "Separate containers for nirmalya, reusable items and dry waste.",
        "Return transport, water and a plan for children and elders.",
      ] },

      { h: "Frequently asked questions" },
      { faq: [
        { q: "When is Anant Chaturdashi in 2026?", a: "Anant Chaturdashi 2026 is Friday, 25 September." },
        { q: "What are the Anant Chaturdashi 2026 tithi timings?", a: "For Mumbai and New Delhi, Drik Panchang gives 11:18 pm on 24 September to 11:06 pm on 25 September. Use a location-specific panchang for your city." },
        { q: "Is Anant Chaturdashi only about Ganesh Visarjan?", a: "No. It is also the Ananta vrata dedicated to Vishnu, with Yamuna, Shesha, the Anant Sutra and the Sushila-Kaundinya katha. Ganeshotsav's final immersion falls on the same day." },
        { q: "What is the Anant Sutra?", a: "It is a sacred thread with fourteen knots worshipped during the Ananta vrata and then tied on the arm. The knots are commonly explained as representing the fourteen worlds." },
        { q: "Which arm is the Anant thread tied on?", a: "A widely published convention is the right arm for men and left arm for women. Family and regional practice can differ, so formal vrata observers should follow their priest or inherited method." },
        { q: "How long should the Anant thread be worn?", a: "Traditions differ. Some remove it after fourteen days and preserve it for later donation; some replace it at the next year's vrata. Follow the custom you received rather than a generic rule." },
        { q: "Who are Sushila and Kaundinya?", a: "They are the central couple in the Ananta vrata-katha. Sushila keeps the vow; Kaundinya rejects the sacred thread, loses prosperity, repents and undertakes the vrata." },
        { q: "Can I do a simple Anant Chaturdashi puja without taking the full vrata?", a: "You can mark the day with a simple Vishnu puja, flowers, tulsi, fruit, prayer and reading. Do not claim to have completed the formal vrata unless you have followed its sankalp and sequence." },
        { q: "What food is offered on Anant Chaturdashi?", a: "Offerings vary. One documented Maharashtrian vrata tradition uses sweet pumpkin puris; homes may also offer fruit, kheer or other prescribed sattvic food. Follow your family method." },
        { q: "Is Ganesh Visarjan on 24 or 25 September in 2026?", a: "The main Anant Chaturdashi Ganesh Visarjan is Friday, 25 September. The tithi begins late on 24 September, which causes two dates to appear in snippets." },
        { q: "Can the Anant Sutra go into Ganesh Visarjan water?", a: "The thread belongs to the Vishnu vrata and is tied on the worshipper's arm. Do not treat it as disposable idol decoration or immerse it unless your received tradition specifically instructs that." },
        { q: "Do I need to fast on Anant Chaturdashi?", a: "Fasting is a common part of the vrata, but strictness varies. Choose the form taught in your tradition and protect health, pregnancy and medication needs." },
      ] },

      { h: "Source and photo credits" },
      { p: "The 2026 date, Mumbai and New Delhi tithi, city-specific puja windows, fourteen-knot explanation and Sushila-Kaundinya katha identification were checked against Drik Panchang on 20 September 2026. The structure of Yamuna, Shesha and thread worship was checked against Sanatan Sanstha's published Ananta Vrat guide. Padmanabha worship, fasting and thread conventions were compared with ISKCON Dwarka's 5 September 2025 article. The two photographs are CC BY-SA 4.0 images from Wikimedia Commons; photographer and licence links appear beneath them." },
      { p: "If someone in your family is keeping the vrat or managing a long visarjan day, a little shagun can become prasad, travel money or dinner after everyone gets home. Send a digi lifafa with your own message and let them use it where the day actually needs it." },
      { related: { href: "/make", label: "Send a digi lifafa" } },
      { related: { href: "/blog/ganesh-visarjan-2026-dates-uttar-puja", label: "Plan the farewell: Ganesh Visarjan dates and Uttar Puja" } },
    ],
  };
