import type { Post } from "../posts";
export const postOrder = 2;

export const post: Post = {
    slug: "sukhkarta-dukhharta-aarti-lyrics-meaning",
    title: "Sukhkarta Dukhharta: full Marathi lyrics, meaning and how to sing the Ganpati aarti",
    date: "2026-09-20",
    updated: "20 September 2026",
    tag: "Festivals",
    excerpt: "Sukhkarta Dukhharta lyrics in Marathi and Roman script, a plain line-by-line meaning, pronunciation notes and its place in Ganpati aarti.",
    body: [
      { p: "Sukhkarta Dukhharta is the Marathi Ganpati aarti that many Maharashtrian homes begin with. Its opening names Ganesha as the maker of happiness and remover of sorrow; its refrain greets him as Mangalmurti, the auspicious form. The three verses move from what he does, to how he appears, to a direct plea for protection in trouble and at life's final passage." },
      { p: "The aarti is traditionally attributed to the seventeenth-century saint Samarth Ramdas. Reference works connect its imagery to Mayureshwar at Morgaon, the first temple in the Ashtavinayak pilgrimage. That background helps explain details people often sing past, including the three eyes and the poet's signature in 'Das Ramacha'." },
      { note: "If you need the words during puja, use the Marathi text below and repeat the dhruvapad, or refrain, after each verse. Sing at the pace your household knows; the aarti is not a performance test." },

      { h: "Sukhkarta Dukhharta lyrics, Hinglish and meaning" },
      { p: "Read each verse in Marathi, use the Roman line directly below it if needed, then read the meaning before moving on. Repeat the refrain after every verse." },
      { h3: "Verse 1" },
      { p: "सुखकर्ता दुःखहर्ता वार्ता विघ्नाची । नुरवी पुरवी प्रेम कृपा जयाची । सर्वांगी सुंदर उटी शेंदुराची । कंठी झळके माळ मुक्ताफळांची ॥१॥" },
      { p: "Sukhakarta dukhaharta, varta vighnachi. Nuravi puravi prem, krupa jayachi. Sarvangi sundar uti shendurachi. Kanthi jhalake maal muktaphalanchi." },
      { p: "Meaning: You bring happiness, remove sorrow and make the trace of obstacles disappear. Your love and grace provide what is needed. Your beautiful form is covered in shendur, and a pearl necklace shines at your throat." },
      { h3: "Refrain" },
      { p: "जय देव जय देव जय मंगलमूर्ती । दर्शनमात्रे मनकामना पुरती ॥धृ॥" },
      { p: "Jai Dev, Jai Dev, Jai Mangalmurti. Darshanmatre manakamana purti." },
      { p: "Meaning: Glory to you, auspicious form. At your darshan, the hopes held in the mind find fulfilment. This is devotional poetry, not a contract for every passing desire." },
      { h3: "Verse 2" },
      { p: "रत्नखचित फरा तुज गौरीकुमरा । चंदनाची उटी कुमकुमकेशरा । हिरेजडित मुकुट शोभतो बरा । रुणझुणती नूपुरे चरणी घागरिया ॥२॥" },
      { p: "Ratnakhachit phara tujh Gaurikumara. Chandanachi uti kumkum-keshara. Hirejadit mukut shobhato bara. Runjhunati nupure charani ghagariya." },
      { p: "Meaning: O son of Gauri, a jewel-studded canopy or ornament adorns you. Sandalwood, kumkum and saffron are applied to your form. A diamond-set crown shines, and anklets ring at your feet. The verse moves like darshan, looking from forehead to feet." },
      { h3: "Verse 3" },
      { p: "लंबोदर पीतांबर फणिवरवंदना । सरळ सोंड वक्रतुंड त्रिनयना । दास रामाचा वाट पाहे सदना । संकटी पावावे निर्वाणी रक्षावे सुरवरवंदना ॥३॥" },
      { p: "Lambodar pitambar phanivaravandana. Saral sond, Vakratunda, Trinayana. Das Ramacha vaat pahe sadana. Sankati pavave, nirvani rakshave, suravaravandana." },
      { p: "Meaning: O large-bellied Lord in yellow cloth, adorned with the serpent; curved-trunked and three-eyed. Your servant Ramdas waits at home. Come in crisis and protect at the final passage, O one worshipped by the gods. Das Ramacha is the poet's signature." },
      { note: "Roman spellings are memory support, not a replacement for listening to a fluent Marathi singer. Learn one verse clearly, then add the next." },

      { h: "Who wrote Sukhkarta Dukhharta?" },
      { p: "The aarti is attributed to Samarth Ramdas, the Marathi saint and poet who lived from 1608 to 1682. Published reference works say the form of Mayureshwar at Morgaon inspired the composition. Morgaon is the foremost shrine in Maharashtra's Ashtavinayak circuit." },
      { p: "Attribution matters because the third verse names Ramdas and because viral captions routinely detach old devotional texts from their author. It also guards against a second confusion: 'Tu Sukhkarta Tu Dukhharta' is a different song. Similar opening words do not make every Ganesh song the Samarth Ramdas aarti." },
      { p: "The standard form has three verses and a refrain repeated after each. Recordings can be much longer because they repeat verses, add instrumental openings, join other aartis, or continue into Ghalin Lotangan and Mantrapushpanjali. Length is not evidence that extra lyrics belong to this composition." },

      { h: "When is it sung during Ganpati puja?" },
      { p: "In many Maharashtrian homes, Sukhkarta Dukhharta is the first aarti in the sequence. During Ganeshotsav it may be sung morning and evening, after the daily puja, at sthapana and during Uttar Puja before visarjan. A household may then sing aarti for other deities, Ghalin Lotangan and Mantrapushpanjali." },
      { p: "Other regions may lead with Jai Ganesh Deva. Neither choice needs to compete with the other. Use the sequence your family or temple follows. If guests do not know Marathi, print the Roman text or invite them to join the refrain instead of rushing through an unfamiliar full verse." },
      { h3: "A safe, simple aarti setup" },
      { ul: [
        "Place the lyrics where the lead singer can see them without leaning over the flame.",
        "Use a stable plate and a manageable number of wicks.",
        "Keep dupattas, sleeves, paper flowers and electrical wires clear.",
        "Let children join beside an adult rather than giving them a crowded plate.",
        "Agree on the tune and pace before beginning if the group comes from different homes.",
        "Repeat the refrain after each of the three verses.",
      ] },

      { h: "Pronunciation notes that change the line" },
      { table: { head: ["Word", "Say it roughly as", "Meaning"], rows: [
        ["Sukhakarta", "su-kha-kar-taa", "maker of happiness"],
        ["Dukhaharta", "du-kha-har-taa", "remover of sorrow"],
        ["Nuravi", "nu-ra-vee", "causes to disappear"],
        ["Shendurachi", "shen-du-raa-chee", "of shendur or vermilion"],
        ["Muktaphalanchi", "muk-ta-pha-laan-chee", "of pearls"],
        ["Mangalmurti", "man-gal-moor-tee", "auspicious form"],
        ["Gaurikumara", "gau-ree-ku-maa-raa", "son of Gauri"],
        ["Trinayana", "tri-na-ya-naa", "three-eyed"],
      ] } },
      { p: "Marathi has dental and retroflex sounds that this rough Roman guide cannot preserve. Listen to a clear recording while following the Devanagari text. Slow the recording if necessary. Learn one verse correctly, then add the next, instead of memorising a blurred six-minute medley." },
      { p: "Household tunes differ slightly. Do not confuse melody variation with a wrong text. Correct words matter; one family sustaining 'Jai Dev' longer than another does not." },

      { h: "Common mix-ups" },
      { ul: [
        "Writing 'Tu Sukhkarta Tu Dukhharta' as if it were the same aarti.",
        "Dropping the second or third verse because a short recording uses only the opening.",
        "Singing 'Das Ramacha' without recognising Ramdas's signature.",
        "Calling Ghalin Lotangan the fourth verse. It is a separate closing prayer.",
        "Treating Mantrapushpanjali as part of the Marathi aarti text.",
        "Copying a Roman spelling that changes nuravi or other words, then translating the typo.",
        "Assuming the longest online medley is the most complete original text.",
      ] },

      { h: "How to teach the aarti without reducing it to memorisation" },
      { p: "Start with the refrain. It is short, returns after every verse, and gives a new singer a real place in the group immediately. Explain Mangalmurti and darshan before asking someone to remember the sounds. Once the refrain is comfortable, learn the first verse in two-line units. Speak each line once, then sing it. Add the second and third verses on later days." },
      { p: "For children who read Devanagari, print the Marathi in a large type size and mark the refrain in another colour. For children who do not, place the Roman line directly beneath the Marathi rather than on a separate page. The goal is to help the eye connect the scripts over time. An English meaning can sit beside the stanza, but do not make someone read a paragraph while the group is already singing the next line." },
      { p: "Ask one concrete question after each verse. What colour is visible in the first? Which sounds can you hear in the second? Who is waiting in the third? The answers, shendur, ringing anklets and Ramdas, turn a sequence of unfamiliar words into an image. The child then knows where they are in the song even if one syllable slips." },
      { p: "Avoid correcting pronunciation in the middle of a family aarti unless the mistake makes the line unrecognisable. Record the word afterward, play it slowly and try again at the next puja. Public correction can make a new singer go silent. A living household tradition survives because people are welcomed into it, not because the most fluent person guards it." },

      { h: "Why one Marathi aarti travels so widely" },
      { p: "The song is brief enough for daily worship and vivid enough to carry a full darshan. It does not spend three verses explaining doctrine. It shows shendur, pearls, sandalwood, saffron, crown, anklets, yellow cloth, serpent and trunk, then lets a devotee stand at the door and ask for help. Someone who understands only part of the Marathi can still follow the movement from praise to seeing to prayer." },
      { p: "Recordings amplified that portability. The Mangeshkar sisters' Ganesh aarti collections became household soundtracks in the late twentieth century, and later music labels, films and online video carried the song beyond Marathi-speaking homes. Available recordings include two-minute studio tracks, six-minute lyrical versions, film arrangements and full aarti sequences. The form changes around the text, but the three verses remain recognisable." },
      { p: "That popularity also creates errors. Captions copy one another. A film version may repeat or rearrange a line for music. Roman titles favour the spellings people type, such as Sukhkarta Dukhharta, while a stricter transliteration gives Sukhakarta Dukhaharta. A useful page should make both searchable without pretending spelling systems are rival prayers." },

      { h: "What comes after Sukhkarta Dukhharta" },
      { p: "There is no single all-India playlist. In a Maharashtrian Ganeshotsav home, the family may continue with Shendur Lal Chadhayo, aarti for Shiva or Devi, Ghalin Lotangan, Mantrapushpanjali and the Ganpati Bappa Morya chant. Another home sings only this aarti and a short prayer. A temple may have a longer established order." },
      { p: "If you are hosting for the first time, ask the oldest participating family member for the usual sequence before printing a booklet. Put each composition under its own heading. This prevents a common internet mistake in which Ghalin Lotangan is pasted under 'full Sukhkarta Dukhharta lyrics' as if it were verse four." },
      { p: "At Uttar Puja, keep the aarti sequence familiar. The day is already emotional and logistically busy. It is not the ideal moment to debut a long medley because it ranked online. Sing the pieces the household can carry together, leave enough time for the farewell prayer, and extinguish or secure the lamp before anyone lifts the idol." },

      { h: "Using a recording without letting it replace the room" },
      { p: "A recording is helpful when nobody present can lead all three verses. Choose one with a clear voice, complete text and a pace the group can follow. Put the speaker near the altar but away from the lamp and puja water. Download or queue it before aarti; advertisements and notifications in the middle of the refrain pull everyone out of the moment." },
      { p: "Keep the volume below the people in the room. The recording should provide pitch and words, not turn the family into an audience. If someone knows the refrain, let them lead it over the track. Once the household becomes confident, lower the volume on later days and eventually sing without it." },
      { p: "Do not assume a video marked 'full' contains the standard three verses. Check the displayed lyrics first. Some uploads loop verse one, attach other prayers or use a film edit. A two-minute recording can contain all three verses at a brisk pace; a six-minute upload can still repeat only part of the text." },

      { h: "How the aarti changes between home, temple and public mandal" },
      { p: "In a home, Sukhkarta Dukhharta often begins with one person lighting the lamp and another leading the first line. Everyone enters at Jai Dev. The tune may be unaccompanied, carried by a small bell, or supported by taal. The scale allows the words to stay audible, and an elder can slow the group if a child is learning." },
      { p: "A temple has an established service schedule, trained pujaris and a local musical habit. The same three verses may be faster because the congregation knows them, or slower because darshan and lamp offerings continue. Visitors should follow the temple lead rather than correcting a line from a family booklet. Temple performance shows one lineage and place, not a command for every household." },
      { p: "A public mandal adds microphones, drums, a large mixed crowd and time pressure. Print the text near the front, choose a lead voice who pronounces Marathi clearly, and turn percussion down during the verse. Let it rise at the refrain if the group prefers. When every instrument plays at full volume through every line, newcomers learn only the tune and none of the words." },
      { p: "Online recordings create a fourth setting: private listening led by a commercial performance. They help with melody and pronunciation, but a household should still know when the three-verse aarti ends. Autoplay can move directly into another composition and make the boundary invisible." },

      { h: "Reading the deity through the song" },
      { p: "The aarti can double as a guide to looking carefully. Before singing, find the shendur, necklace, crown, yellow garment, trunk and feet in the image or murti. Not every representation will contain every feature. A white marble Ganesha may not be covered in shendur; a framed print may show a different crown; many images have two eyes rather than the Trinayana named in the song." },
      { p: "That mismatch is not a puja error. The composition evokes Mayureshwar and a particular poetic darshan. Hindu image traditions hold many Ganesha forms at once. Use the difference to ask what remains stable: elephant head, curved trunk, generous belly, auspicious presence and the relationship to Gauri." },
      { p: "The sensory sequence also explains the role of the lamp. Pearls gleam, jewels shine, anklets sound and sandalwood or saffron carry fragrance. Aarti is not only a text recited toward an object. It gathers sight, sound, smell, movement and food into one act of attention." },

      { h: "Translating devotional poetry without flattening it" },
      { p: "A literal translation helps with nouns, but it can miss the movement of a line. 'Varta vighnachi' is not merely 'news of obstacles'; paired with nuravi, it imagines even their trace or report disappearing. 'Mera manakamana purti' is not a vending-machine promise; it places desire inside darshan, where the person asking may also be changed." },
      { p: "Names should often remain names. Lambodar is richer than only 'fat-bellied'; Vakratunda carries an icon and a theology of overcoming crookedness; Mangalmurti is more intimate in Maharashtrian worship than the flat phrase 'auspicious idol'. Give the basic meaning, then keep the name available for the reader to learn." },
      { p: "Where a compound is disputed, say so. Phanivaravandana and the precise object denoted by phara receive different explanations. A trustworthy page should not select the most dramatic translation because it reads well. Preserve the line, explain the secure part and mark what remains uncertain." },

      { h: "A seven-day learning plan" },
      { table: { head: ["Day", "What to do"], rows: [
        ["1", "Read verse 1 in Marathi and understand shendur, pearls, obstacles and grace"],
        ["2", "Speak verse 1 in rhythm, then add the refrain"],
        ["3", "Learn verse 2 by tracing the adornment from forehead to feet"],
        ["4", "Sing verses 1 and 2 without looking at Roman text"],
        ["5", "Learn verse 3 and identify Ramdas's signature"],
        ["6", "Sing all three slowly with the refrain after each"],
        ["7", "Lead a short home aarti and note only the words that still need work"],
      ] } },
      { p: "Ten focused minutes is enough each day. Record your own spoken version before recording a performance. Listening back reveals swallowed consonants more clearly than singing louder. If Marathi is new, ask a speaker to correct two or three words at a time, not every accent feature in one sitting." },

      { h: "Questions to ask an elder about your family's version" },
      { ul: [
        "Which aarti comes immediately before and after this one?",
        "Does the family sing all three verses every day or only during Ganeshotsav?",
        "Which tune and tempo came from the grandparents' home?",
        "Are there words the family pronounces differently from printed text?",
        "Who holds the lamp, who rings the bell and when does everyone receive aarti?",
        "What offering is normally ready before the song begins?",
      ] },
      { p: "Write the answers beside the lyrics. Ritual knowledge often disappears not because nobody cared, but because everyone assumed the sequence was obvious. A one-page note can preserve more than a folder of generic festival downloads." },

      { lifafaCta: { text: "Learning this aarti for someone you love? Add a personal blessing and send the shagun with the same care.", label: "Make their Digi Lifafa" } },

      { h: "If Marathi is not spoken at home" },
      { p: "Keep the Marathi text primary and let the meaning carry participation. One person can read the plain meaning before each verse for the first few days. Guests then know the image they are about to sing. Do not replace the aarti with an improvised English rhyme and call it a translation; prose meaning and original song can sit beside each other." },
      { p: "Ask a Marathi speaker to send one slow voice note of the spoken verses. Save it with the date and their name, not as an anonymous forward. A family archive that preserves the voice of an aunt, grandfather or friend can become more meaningful than a studio track." },

      { h: "Frequently asked questions" },
      { faq: [
        { q: "What does Sukhkarta Dukhharta mean?", a: "It means the maker of happiness and remover of sorrow. The opening addresses Ganesha as the one who removes obstacles through love and grace." },
        { q: "Who wrote Sukhkarta Dukhharta?", a: "The Marathi aarti is traditionally attributed to the seventeenth-century saint Samarth Ramdas." },
        { q: "How many verses does Sukhkarta Dukhharta have?", a: "The standard aarti has three verses and a refrain, Jai Dev Jai Dev Jai Mangalmurti, repeated after each verse." },
        { q: "Is Sukhkarta Dukhharta in Marathi or Sanskrit?", a: "It is a Marathi aarti. It includes devotional names with Sanskrit roots, but its language and grammar are Marathi." },
        { q: "When should Sukhkarta Dukhharta be sung?", a: "It is commonly sung during Ganesh puja, often first in the Maharashtrian aarti sequence, and during morning or evening worship, sthapana and Uttar Puja." },
        { q: "Is Ghalin Lotangan part of Sukhkarta Dukhharta?", a: "No. Ghalin Lotangan is a separate closing prayer often sung later in the same aarti sequence." },
        { q: "What is the meaning of Mangalmurti?", a: "Mangalmurti means the auspicious form, a name praising Ganesha as the embodiment of blessing and good beginnings." },
        { q: "Why does the aarti call Ganesha Trinayana?", a: "Trinayana means three-eyed. The image is associated in commentary with Mayureshwar at Morgaon, whose form helped inspire the aarti." },
        { q: "What does Das Ramacha mean?", a: "It points to Ramdas, servant of Rama. It is the poet's signature before he says he waits for Ganesha at home." },
        { q: "Can I sing only the first verse?", a: "A short household aarti may use the first verse, but the standard composition has three. If publishing or teaching the full aarti, include all three and the refrain." },
        { q: "Which recording should I learn from?", a: "Choose a clear Marathi recording that displays all three verses accurately. Follow the Devanagari text and use slow playback rather than relying only on Roman captions." },
        { q: "Is the aarti sung only on Ganesh Chaturthi?", a: "No. It is sung in regular Ganesh worship and temples throughout the year, though Ganeshotsav makes it especially prominent." },
      ] },

      { h: "Source note" },
      { p: "The authorship, three-verse structure, Mayureshwar connection and verse commentary were checked against published reference material summarised on the Sukhakarta Dukhaharta reference page, which cites Prarthana: A Book of Hindu Psalms and Sacred Songs of India. Lyrics and meaning were compared across that reference text and Eternal Raga on 20 September 2026." },
      { p: "If you are singing aarti for someone you cannot celebrate with in person, send the shagun with the same care as the song. A digi lifafa lets you add your own message and gives them something useful for prasad, flowers or the family meal." },
      { related: { href: "/make", label: "Send a Digi Lifafa" } },
      { related: { href: "/blog/ganesh-visarjan-2026-dates-uttar-puja", label: "Read next: how to plan Ganesh Visarjan and Uttar Puja" } },
    ],
  };
